/* data.js */
const companies = [
  {
    id: "abs-global",
    name: "ABS Global, Inc.",
    shortTitle: "Global Bovine Genetics Leader",
    type: "standard",
    animalTypes: ["Bovine (Dairy & Beef)"],
    country: "United States of America",
    lat: 43.2066,
    lng: -89.3423,
    address: "1525 River Road, DeForest, WI 53532",
    website: "https://absglobal.com",
    phone: "1-800-227-7883",
    email: "NAm.hr@genusplc.com",
    description: "Headquartered in Wisconsin, ABS Global leads worldwide in bovine genetics, reproduction services, and technologies. Markets in over 70 countries and pioneers innovations like Sexcel sexed semen.",
    services: ["Semen Production", "Sexed Genetics", "Genetic Consulting", "Udder Care"],
    image: "https://via.placeholder.com/150"
  },
  {
    id: "genex-coop",
    name: "Genex Cooperative",
    shortTitle: "Cooperative Genetics Provider",
    type: "standard",
    animalTypes: ["Bovine (Dairy & Beef)"],
    country: "United States of America",
    lat: 44.7766,
    lng: -88.6083,
    address: "117 E Green Bay St, Shawano, WI 54166",
    website: "https://genex.coop",
    phone: "888-333-1783",
    email: "info@genex.coop",
    description: "Farmer-owned cooperative under URUS delivering high-quality bovine genetics, herd care products, and reproductive solutions.",
    services: ["Semen Sales", "Genetic Programs", "Herd Management", "Calf Health"],
    image: "https://via.placeholder.com/150"
  },
  {
    id: "st-genetics",
    name: "STgenetics",
    shortTitle: "Sexed Semen Innovator",
    type: "standard",
    animalTypes: ["Bovine"],
    country: "United States of America",
    lat: 30.3879,
    lng: -96.0877,
    address: "22575 State Highway 6 S, Navasota, TX 77868",
    website: "https://stgen.com",
    phone: "(936) 870-3960",
    email: "contact@stgen.com", 
    description: "Global leader in sex-sorted semen, embryo production, and sustainable bovine genetics advancement through science and technology.",
    services: ["Sexed Semen Sorting", "Embryo Production", "Genomic Testing", "EcoFeed Programs"],
    image: "https://via.placeholder.com/150"
  },
  {
    id: "select-sires",
    name: "Select Sires, Inc.",
    shortTitle: "Premier Genetics Cooperative",
    type: "standard",
    animalTypes: ["Bovine (Dairy & Beef)"],
    country: "United States of America",
    lat: 40.1064,
    lng: -83.2680,
    address: "11740 U.S. 42 North, Plain City, OH 43064",
    website: "https://selectsires.com",
    phone: "(614) 873-4683",
    email: "info@selectsires.com",
    description: "Farmer-owned federation providing highly fertile bovine semen and genetic consulting through domestic cooperatives and World Wide Sires.",
    services: ["Semen Production", "Genetic Selection", "Reproductive Programs"],
    image: "https://via.placeholder.com/150"
  },
  {
    id: "jetstream-gen",
    name: "Jetstream Genetics",
    shortTitle: "Elite Holstein Genomics",
    type: "standard",
    animalTypes: ["Bovine (Holstein)"],
    country: "United States of America",
    lat: 43.1947,
    lng: -88.7246,
    address: "Watertown, WI 53094",
    website: "https://urus.org",
    phone: "Contact via URUS",
    email: "info@urus.org",
    description: "Supplies breed-defining Holstein sires from top genomic sources, including deep pedigrees and extreme traits.",
    services: ["Sire Marketing", "Genomic Selection"],
    image: "https://via.placeholder.com/150"
  },
  {
    id: "ww-sires",
    name: "World Wide Sires",
    shortTitle: "Global Semen Exporter",
    type: "standard",
    animalTypes: ["Bovine"],
    country: "United States of America",
    lat: 36.3302,
    lng: -119.2921,
    address: "5545 Avenida De Los Robles, Visalia, CA 93291",
    website: "https://wwsires.com",
    phone: "(559) 622-2222",
    email: "info@wwsires.com",
    description: "Subsidiary of Select Sires; largest exporter of U.S. bovine semen with international marketing focus.",
    services: ["Semen Export", "International Distribution", "Genomic Sires"],
    image: "https://via.placeholder.com/150"
  },
  {
    id: "trans-ova",
    name: "Trans Ova Genetics",
    shortTitle: "Reproductive Tech Provider",
    type: "standard",
    animalTypes: ["Bovine"],
    country: "United States of America",
    lat: 43.0784,
    lng: -96.1764,
    address: "2938 380th St, Sioux Center, IA 51250",
    website: "https://transova.com",
    phone: "(712) 722-3586",
    email: "info@transova.com",
    description: "Industry leader in bovine reproductive technologies, including embryo transfer and IVF for livestock breeders.",
    services: ["Embryo Transfer", "IVF", "Genetic Preservation", "Cloning"],
    image: "https://via.placeholder.com/150"
  },
  {
    id: "androgenics",
    name: "Androgenics",
    shortTitle: "Custom Semen Collection",
    type: "standard",
    animalTypes: ["Bovine"],
    country: "United States of America",
    lat: 37.7663,
    lng: -120.8436,
    address: "11240 26 Mile Road, Oakdale, CA 95361",
    website: "https://androgenicsinc.com",
    phone: "(209) 847-1101",
    email: "info@androgenicsinc.com",
    description: "NAAB/CSS participant focused on high-fertility custom semen collection and processing.",
    services: ["Semen Collection", "Freezing", "Storage", "Export"],
    image: "https://via.placeholder.com/150"
  },
  {
    id: "champion-gen",
    name: "Champion Genetics",
    shortTitle: "Reproduction Facility",
    type: "standard",
    animalTypes: ["Bovine", "Deer"],
    country: "United States of America",
    lat: 32.5555,
    lng: -95.8640,
    address: "18035 FM 17, Canton, TX 75103",
    website: "https://championgenetics.com",
    phone: "(903) 567-4044",
    email: "championgenetics@yahoo.com",
    description: "Family-operated custom collection center offering semen and embryo services for cattle and deer.",
    services: ["Semen Collection", "Embryo Transfer", "AI Training"],
    image: "https://via.placeholder.com/150"
  },
  {
    id: "elgin-breeding",
    name: "Elgin Breeding Service",
    shortTitle: "Custom Collection Pioneer",
    type: "standard",
    animalTypes: ["Bovine"],
    country: "United States of America",
    lat: 30.3508,
    lng: -97.3683,
    address: "875 Central Ave, Elgin, TX 78621",
    website: "https://elginbreedingservice.com",
    phone: "(512) 285-2019",
    email: "info@elginbreedingservice.com",
    description: "Family tradition since 1954; specializes in quality custom semen collection and export.",
    services: ["Semen Harvesting", "Storage", "Shipping", "Health Testing"],
    image: "https://via.placeholder.com/150"
  },
  {
    id: "hawkeye-breeders",
    name: "Hawkeye Breeders Service",
    shortTitle: "Custom Collection Facility",
    type: "standard",
    animalTypes: ["Bovine (Beef & Dairy)"],
    country: "United States of America",
    lat: 41.6144,
    lng: -94.0321,
    address: "32642 Old Portland Road, Adel, IA 50003",
    website: "https://hawkeyebreeders.com",
    phone: "(515) 993-4711",
    email: "info@hawkeyebreeders.com",
    description: "Established 1969; provides custom semen collection and fertility testing with modern technology.",
    services: ["Semen Collection", "Bull Boarding", "Fertility Testing"],
    image: "https://via.placeholder.com/150"
  },
  {
    id: "origen-beef",
    name: "ORIgen, Inc.",
    shortTitle: "Breeder-to-Breeder Genetics",
    type: "standard",
    animalTypes: ["Bovine (Beef)"],
    country: "United States of America",
    lat: 45.9080,
    lng: -108.3101,
    address: "10 West Arrow Creek Road, Huntley, MT 59037",
    website: "https://origenbeef.org",
    phone: "1-866-867-4436",
    email: "info@origenbeef.org",
    description: "Connects bull owners to global marketplace with breeder-focused marketing and collection.",
    services: ["Semen Collection", "Marketing", "Embryo Technologies"],
    image: "https://via.placeholder.com/150"
  },
  {
    id: "rocky-mtn-sire",
    name: "Rocky Mountain Sire Services",
    shortTitle: "Custom Bull Stud",
    type: "standard",
    animalTypes: ["Bovine"],
    country: "United States of America",
    lat: 39.7578,
    lng: -104.4283,
    address: "1616 N Manila Road, Bennett, CO 80102",
    website: "https://rmssbulls.com",
    phone: "(303) 644-3246",
    email: "info@rmssbulls.com",
    description: "Independent custom semen collection since 1992; serves Midwest and beyond with high-conception products.",
    services: ["Semen Collection", "Boarding", "Storage", "Health Testing"],
    image: "https://via.placeholder.com/150"
  },
  {
    id: "sek-genetics",
    name: "SEK Genetics",
    shortTitle: "Beef Repro Services",
    type: "standard",
    animalTypes: ["Bovine (Beef)", "Small Ruminant"],
    country: "United States of America",
    lat: 37.4705,
    lng: -95.3562,
    address: "9525 70th Road, Galesburg, KS 66740",
    website: "https://sekgenetics.com",
    phone: "800-443-6389",
    email: "info@sekgenetics.com",
    description: "Diverse operation with large beef semen inventory, veterinary repro services, and in-house lab testing.",
    services: ["Semen Sales", "Embryo Transfer/IVF", "Veterinary Care", "Disease Testing"],
    image: "https://via.placeholder.com/150"
  }
  {
    id: "comp_001",
    name: "AgriGenetics Lab",
    shortTitle: "Bovine IVF Center",
    type: "validated", // options: 'standard', 'validated', 'testing'
    animalTypes: ["Cattle", "Sheep"],
    country: "United States of America", // Must match GeoJSON country name
    lat: 40.7128,
    lng: -74.0060,
    address: "123 Science Dr, New York, NY",
    website: "https://example.com",
    phone: "+1 555 0199",
    email: "contact@agrigenetics.com",
    description: "Leading laboratory for bovine in-vitro fertilization and genetic analysis.",
    services: ["Semen Analysis", "Genetic Screening", "Embryo Transfer"],
    image: "https://via.placeholder.com/150", // Replace with real image URL
  },
  {
    id: "comp_002",
    name: "UniVet Research",
    shortTitle: "University Partner",
    type: "standard",
    animalTypes: ["Horses", "Pigs"],
    country: "Germany",
    lat: 52.5200,
    lng: 13.4050,
    address: "University Sq 1, Berlin",
    website: "https://berlin-univet.de",
    phone: "+49 30 123456",
    email: "info@univet.de",
    description: "University department focused on equine reproduction studies.",
    services: ["Research", "Clinical Trials"],
    image: "https://via.placeholder.com/150",
  },
  {
    id: "comp_003",
    name: "BioTest Farms",
    shortTitle: "Beta Tester",
    type: "testing",
    animalTypes: ["Goats"],
    country: "France",
    lat: 48.8566,
    lng: 2.3522,
    address: "Rue de la Ferme, Paris",
    website: "https://biotest.fr",
    phone: "+33 1 23 45 67 89",
    email: "hello@biotest.fr",
    description: "Currently testing the new MAKSA validation protocols on goat herds.",
    services: ["Herd Management"],
    image: "https://via.placeholder.com/150",
  }
];
